tap jgonzales/php

install zsh zsh-completions
install grc
install coreutils
install spark
install git git-flow
install node
install dnsmasq
install imagemagick
install ffmpeg
install memcached
install php55 php55-mcrypt php55-memcache php55-imagick
install mysql
install phpmyadmin
